[package]
name = "erosion"
version = "0.1.0"
edition = "2018"
authors = ["Eric (Skepz) <skepz.dev@gmail.com>"]
description = "A 2D game engine where all pixels are simulated"

[dependencies]
wgpu = "*"
winit = "*"
cgmath = "*"
env_logger = "*"
log = "*"
futures = "*"